Use ES6 syntax.
digitalbazaar/bedrock-angular-credential pull request #17
Opened 2017-05-23 14:42 UTC by mattcollier

@davidlehn interested in eliminating this file if it's not needed:
https://github.com/digitalbazaar/bedrock-angular-credential/blob/master/credential-routes.js

2017-05-23 18:12 UTC, dlongley requested changes

2017-05-23 18:12 UTC, dlongley commented on credential-directive.js
> +              credential);
Was this over 80 chars?

2017-05-23 18:12 UTC, dlongley commented on credential-directive.js
> +              'simple') {
Over 80 chars?

2017-05-23 18:12 UTC, dlongley commented on credential-service.js
> +  config) {
Drop one, drop 'em all

2017-05-23 18:12 UTC, dlongley commented on credential-service.js
> +    types = _.reject(types, function(type) { return type === 'Credential';});
Weird: A space after the opening `{` but no space before the closing `}`? Should be consistent.

2017-05-23 18:12 UTC, dlongley commented on credential-viewer-component.js
> +  $scope.$watch(function() { return self.credential;}, function(credential) {
Inconsistent brace spacing

2017-05-23 18:12 UTC, dlongley commented on credentials-list-directive.js
> +  config) {
Drop one, drop em all

2017-05-23 19:09 UTC, mattcollier commented on credential-directive.js
> +              credential);
fixed.

2017-05-23 19:10 UTC, mattcollier commented on credential-directive.js
> +              'simple') {
fixed.

2017-05-23 19:10 UTC, mattcollier commented on credential-service.js
> +  config) {
fixed.

2017-05-23 19:10 UTC, mattcollier commented on credential-service.js
> +    types = _.reject(types, function(type) { return type === 'Credential';});
fixed.

2017-05-23 19:11 UTC, mattcollier commented on credential-viewer-component.js
> +  $scope.$watch(function() { return self.credential;}, function(credential) {
fixed.

2017-05-23 19:11 UTC, mattcollier commented on credentials-list-directive.js
> +  config) {
fixed.

2017-05-23 19:12 UTC, mattcollier commented
@dlongley ready for another pass.

2017-05-23 19:23 UTC, dlongley approved these changes

2017-05-23 21:22 UTC, davidlehn commented
I'm not sure what to do about those unused routes.  This module and the idp code are still hooked together a bit it seems.  The idp is actually using the view html template from this module.  But each have their own credentials.html.  We should figure out if things have progressed enough that we could fix up this situation in some appropriate way.

2017-05-26 17:28 UTC, mattcollier commented
@davidlehn the routes are commented out in the release version.  So I'm confused about why we can't just eliminate the file.

2017-05-26 18:12 UTC, davidlehn commented
@mattcollier Looking at the history of that file I can't recall what was going on. Was the intent to remove those routes from this module eventually?  Or to re-enable them once something else was fixed?  Yeah the file could be removed now if the intent was to never use those routes here.  If you understand the various interacting modules and where things should go, then do what is best.

2017-05-26 18:32 UTC, mattcollier commented
@davidlehn unfortunately I don't know the answers to those questions.

2017-05-30 19:53 UTC, merged